name: Build Jenkins Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  main:
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: 'jenkins-base'
      CATEGORY: util
      GH_REGISTRY: docker.pkg.github.com/codezenith
      USERNAME: DerPauli

    steps:

      - name: Get VCS
        uses: actions/checkout@v2
        
      - name: Build Dockerfile
        run: docker build -t "${{ env.CONTAINER_NAME }}" --build-arg KST_PASS="${{ secrets.KST_PASS }}" --build-arg DOCKER="true" --build-arg CERT="true" .
        
      - name: Authenticate with registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ env.USERNAME }}" --password-stdin
        
      - name: Tag Image
        run: docker tag "${{ env.CONTAINER_NAME }}" "${{ env.GH_REGISTRY }}/${{ env.CATEGORY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}"
        
      - name: Tag Latest
        run: docker tag "${{ env.CONTAINER_NAME }}" "${{ env.GH_REGISTRY }}/${{ env.CATEGORY }}/${{ env.CONTAINER_NAME }}:latest"
        
      - name: Push Image
        run: |
          docker push "${{ env.GH_REGISTRY }}/${{ env.CATEGORY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}"
          docker push "${{ env.GH_REGISTRY }}/${{ env.CATEGORY }}/${{ env.CONTAINER_NAME }}:latest"

